### ISSUE TITLE
[Bug] Cannot remove categories/packages from donor shop on website using control panel

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [CraftingStore/MinecraftPlugin#11]
I must say, you sure do like making it difficult to report bugs for the website. So guess I'll report it here even if this is for the plugin.

For free plan it won't work to remove packages/tabs. I keep trying but it keeps showing tabs/categories & packages I've already removed or disabled in the control panel. 

Please fix..

**Comment by Tim-NL** [comment]
Hi,

You can use our suggestions & bugs repository for global bug reports: https://github.com/CraftingStore/Suggestions
And you can use our support ticket at craftingstore.net for store specific issues like this one.

We do not "make it difficult". We always link to the suggestions & bugs board. When you click on "Support" on the dashboard and create a ticket, we provide a link with the following message;
"I have checked the suggestions/issue tracker located here." - This is linking to the page

And this is also described in the information channel on our Discord server. The Discord server is also linked at the dashboard, on the homepage.

And if you are not on Discord, you can also add our chatbot that is on the homepage, and on the support section of our dashboard. This will link you to the correct repository as well.

-Tim
