### ISSUE TITLE
Donation Commands Run Twice

### ISSUE THREAD

**Issue by meowsome** [CraftingStore/MinecraftPlugin#12]
Hello,

I have an issue with the CraftingStore plugin, and I think I may have an idea about what is causing it but I am not 100% sure.

Sometimes, when the commands for a purchased package are executed, they execute twice, once right after the other. This is problematic for my network because some of the items players can purchase are crate keys, and if they purchase 1 crate key they sometimes get 2.

I believe this may be due to the player holding something in their off hand and their main hand at the same time. I asked the player who this error occurred with, and he said his entire inventory was full except for one item slot which he opened up for a key (that item slot ended up getting filled with both keys which stacked together). I found this issue that isn't the exact same but is related: https://www.spigotmc.org/threads/playerinteractevent-running-twice.286968/

Here is an example of what this looks like in the console (I replaced the player's name with \<playername\>):
```
[11:35:38] [Server thread/INFO]: <playername> issued server command: /buy
[11:46:15] [Server thread/INFO]: Crates ✦ You have given <playername> 1 Keys.
[11:46:17] [Server thread/INFO]: Crates ✦ You have given <playername> 1 Keys.
```

Can somebody look into this? Thank you! I've really been enjoying CraftingStore.

**Comment by Tim-NL** [comment]
Hi,

Could you open a ticket on our dashboard and provide us with things like the transaction ID for this payment? This is not related to the plugin, so we'd prefer to look into the store itself.

-Tim
