### ISSUE TITLE
CraftingStore Plugin Error

### ISSUE THREAD

**Issue by EkonC** [CraftingStore/MinecraftPlugin#13]
Hello, I have been recently getting these errors in my server console and I am not sure what to do about it.

https://pastebin.com/tWj0F64L

This server is running Paper version git-**Paper-478** (MC: **1.16.5**) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Plugins (41):** AdvancedEnchantments, AdvancedMonthlyCrates, AuctionHouse, BottledExp, BungeeGuard, Citizens, ClearLag, CMI, CMILib, CMIPaperLib, CoreProtect, CraftingStore, DiscordSRV, DragonSlayer, Duels, InventoryRollback, Jobs, KeepDeathDrop, LuckPerms, Matrix, MobFarmManager, Multiverse-Core, PlaceholderAPI, Plan, ProtectionLib*, ProtocolLib, QuickShop, Residence, SkinsRestorer, TAB, TradeMe, TryMe, TutorialCreator, UltimateCatcher, Vault, Votifier, VotingPlugin, WorldEdit, WorldEditGlobalizerBukkit*, WorldGuard, WorldGuardExtraFlags

If you think you can help me out with this and need more info, I can provide you with that in a reply.

**Comment by Tim-NL** [comment]
Hi,

The issue that you are having is this one in the error: "java.lang.OutOfMemoryError".

Your server does not have enough memory (RAM) to run. You should either remove some plugins or add more memory to the server. This is not an issue within the plugin itself. Just a lack of system resources.

-Tim
