### ISSUE TITLE
API - Manual Transactions

### ISSUE THREAD

**Issue by BluBoy3ch0** [CraftingStore/MinecraftPlugin#15]
Unsure if this is just me, but the DonationsReceivedEvent doesn't fire for manual transactions.

**Comment by Tim-NL** [comment]
Hi,

It will fire for every command (the naming is a bit off, it was named like this in the first version of the plugin and we haven't removed it because plugins are using it). 

So if no commands are configured for a package, it won't run.

-Tim

**Comment by BluBoy3ch0** [comment]
> Hi,
> 
> It will fire for every command (the naming is a bit off, it was named like this in the first version of the plugin and we haven't removed it because plugins are using it).
> 
> So if no commands are configured for a package, it won't run.
> 
> -Tim

strange, was pretty sure a command was there but I will double check and try again, thanks.

**Comment by BluBoy3ch0** [comment]
> Hi,
> 
> It will fire for every command (the naming is a bit off, it was named like this in the first version of the plugin and we haven't removed it because plugins are using it).
> 
> So if no commands are configured for a package, it won't run.
> 
> -Tim

perhaps also deprecate the event and just make a new one. the old one can still run but just have a new one that changes the name of it. could clear it up.
