### ISSUE TITLE
Using the API

### ISSUE THREAD

**Issue by ItzCreeperBoy27** [CraftingStore/MinecraftPlugin#7]
Is this the correct way to use getUsername() or am I doing somthing wrong because I am getting errors in eclipse. I did import net.craftingstore.bukkit.events.*

String p = DonationReceivedEvent.this.getUsername();

**Comment by ItzCreeperBoy27** [comment]
Eclipse Error

Multiple markers at this line
	- The method getUsername() from the type DonationReceivedEvent is 
	 deprecated
	- No enclosing instance of the type DonationReceivedEvent is accessible

**Comment by thijsa** [comment]
You need to use the Spigot / Bukkit event API, as explained on their website: https://www.spigotmc.org/wiki/using-the-event-api/.

The fired event is DonationReceivedEvent, but you have already found that one.

So your code would look something like this:
```
public class TestListener implements Listener {

    @EventHandler
    public void onDonation(DonationReceivedEvent donationReceivedEvent) {
        System.out.println("Donation received from " + donationReceivedEvent.getDonation().getPlayer().getUsername());
    }

}
```

**Comment by Tim-NL** [comment]
I've closed the issue, feel free to comment if you believe that the information provided is not enough information. 

-Tim
